Repository mico-members/miracle-coding-blog, pull requests merged in 2021-08, with the labels that each got.

#5 fix, style: [#4] import React 에러 해결 및 indent 스타일 통일
  package.json
  src/App.tsx
  src/components/Foo.tsx
  src/components/Root.tsx
  src/components/header/Header.tsx
  src/components/header/Label.tsx
  tsconfig.json
  webpack.config.js
Labels: error

#8 [#7] Feature : filter & store
  src/components/Foo.tsx
  src/components/Root.tsx
  src/config/store/store.tsx
Labels: feature

#10 [#9] HeaderFilter구현
  src/components/header/Header.tsx
  src/components/header/filter/Author.tsx
  src/components/header/filter/Filter.tsx
Labels: feature

#11 [#6] feat: Infinite scrolling
  .gitignore
  package.json
  src/components/Foo.tsx
  src/components/Root.tsx
  src/components/body/Body.tsx
  src/components/body/list/ArticleItem.tsx
  src/components/body/list/Articles.tsx
  src/components/header/filter/Filter.tsx
  src/config/atoms.tsx
  src/config/store/store.tsx
  src/config/types/componentTypes.ts
  webpack.config.js
Labels: feature

#21 [#17] fix: BodyParser 수정
  src/components/body/list/Articles.tsx
  src/config/store/store.tsx
  src/config/types/dataTypes.ts
Labels: enhancement

#29 [#16] feat: 스켈레톤 UI 추가
  src/components/body/list/Articles.tsx
  src/components/body/list/skeleton/ArticleItemSkeleton.tsx
  src/components/body/list/skeleton/ArticlesSkeleton.tsx
  src/config/style/theme.ts
  src/config/types/stylesTypes.ts
Labels: feature

#39 Fix _ ver 0.0.2
  src/components/body/side/SideFilter.tsx
  src/components/header/Header.tsx
  src/components/header/Label.tsx
  src/components/header/filter/Author.tsx
  src/components/header/filter/Filter.tsx
  src/components/header/filter/FilterModal.tsx
  src/config/store/store.tsx
  src/config/types/dataTypes.ts
  webpack.config.js
Labels: bug
